#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use Minicli\Command\CommandCall;

$app = new App([
    'app_path' => __DIR__ . '/app/Command',
    'debug' => false,
    'theme' => 'App\Theme\Blue'
    //'theme' => '\Unicorn'
]);

// Example basic command registered via a closure:
$app->setSignature('./minicli about');
$app->registerCommand('about', function(CommandCall $input) use ($app) {
    $app->getPrinter()->display(
        $app->getPrinter()->filterOutput("PHP CLI Application Demo", "alt") .
        "\nSherri Wheeler @SyntaxSeed." .
        "\nCreated with github.com/minicli/minicli." .
        $app->getPrinter()->filterOutput("\nUse the 'help' command to see a list of available commands.", "italic")
    );
});


$app->runCommand($argv);
